# Generated by Django 3.2.8 on 2022-11-08 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_auto_20221029_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='fechaActual',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la publicacion'),
        ),
    ]
