# Generated by Django 3.2.8 on 2022-11-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_alter_mascotas_fechaactual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='fechaActual',
        ),
    ]
